spring:
  datasource:
    url: jdbc:mysql://localhost:3306/air_travel?useSSL=false&serverTimezone=UTC
    username: root
    password: stitch
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always
server:
  port: 8080
