spring:
  datasource:
    url: jdbc:mysql://localhost:3306/air_travel?sslMode=PREFERRED&serverTimezone=UTC
    username: air_user
    password: Air123!secure
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080